import Head from "next/head";
import * as React from "react";
import { Container, Box, CssBaseline } from "@mui/material";
import Header from "../components/Header";
import MangaList from "../components/MangaList";
export default function Home() {
  return (
    <>
      <Head>
        <title>Manga Reader</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <Box sx={{ display: "flex", p: 3, mt: 8 }} component="main">
        <CssBaseline />
        <MangaList />
        {/* <Container
          sx={{ justifyItems: "left", alignItems: "flex-start" }}
        ></Container> */}
      </Box>
    </>
  );
}
