import Head from "next/head";
import * as React from "react";
import { Box, CssBaseline, useScrollTrigger, Fab, Zoom } from "@mui/material";
import Header from "../components/Header";
import MangaList from "../components/MangaList";
import { useEffect, useCallback } from "react";

export default function Home() {
  const [chapters, setChapters] = React.useState([]);

  useEffect(() => {
    const getChapters = async (limit = 50, offset = 0) => {
      let mangaList = await fetch(
        "/api/chapters?limit=" + limit + "&offset=" + offset
      );
      const data = await mangaList.json();
      setChapters(data.chapters);
    };

    getChapters();
  }, []);

  const trigger = useScrollTrigger({
    threshold: 100,
  });

  const scrollToTop = useCallback(() => {
    window.scrollTo({ top: 0, behavior: "smooth" });
  }, []);

  return (
    <>
      <Head>
        <title>Manga Reader</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <Box
        sx={{
          display: "flex",
          p: 3,
          mt: 8,
          width: {
            xs: "100%",
            sm: "100%",
            md: "90%",
            lg: "80%",
            xl: "60%",
          },
        }}
        component="main"
      >
        <CssBaseline />
        <MangaList chapters={chapters} />
      </Box>
    </>
  );
}
